services:
  - type: web
    name: lms-backend
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: CORSMIDDLEWARE_ALLOW_ORIGINS
        value: "*" # Update this with your frontend URL later
    autoDeploy: true
    rootDir: backend

databases:
  - name: lms-db
    databaseName: lms
    user: lms_user
    plan: free # Tier for the database
